version: "3.3"

networks:
  test-network:

services:

  localstack:
    container_name: localstack
    image: 'localstack/localstack:0.12.6'
    restart: always
    ports:
      - '4566:4566'
    environment:
      - DEFAULT_REGION=eu-west-1
      - LAMBDA_EXECUTOR=docker
      - DOCKER_HOST=unix:///var/run/docker.sock
    networks:
      - test-network
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"